apiVersion: v1
kind: Secret
metadata:
  name: xroad-metrics-credentials
type: Opaque
data:
  rootUser: {{ .Values.database.auth.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.database.auth.rootPassword | b64enc | quote }}
  analyzerPassword: {{ .Values.database.auth.analyzerPassword | b64enc | quote }}
  analyzerInterfacePassword: {{ .Values.database.auth.analyzerInterfacePassword | b64enc | quote }}
  anonymizerPassword: {{ .Values.database.auth.anonymizerPassword | b64enc | quote }}
  collectorPassword: {{ .Values.database.auth.collectorPassword | b64enc | quote }}
  correctorPassword: {{ .Values.database.auth.correctorPassword | b64enc | quote }}
  reportsPassword: {{ .Values.database.auth.reportsPassword | b64enc | quote }}
