apiVersion: v1
kind: Service
metadata:
  name: subscriber-mock
spec:
  selector:
    app: subscriber-mock
  ports:
    {{- range .Values.service.ports }}
    - protocol: TCP
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
    {{- end }}
  type: {{ .Values.service.type }}
