apiVersion: v2
name: xroad-metrics
description: A Helm chart for deploying X-Road-Metrics into IM-BB Kubernetes cluster

type: application
# The version of the helm chart shall follow the version of X-Road-Metrics.
version: 1.1.1
# This is the version number of the X-Road.Metrics release.
appVersion: "1.1.1"

dependencies:
  # X-Road-Metrics Database Module
  - alias: database
    name: mongodb
    version: 13.15.3
    repository: oci://registry-1.docker.io/bitnamicharts
  # X-Road-Metrics Collector Module
  - alias: collector
    name: collector
    version: 1.1.1
    repository: file://./charts/corrector
  # X-Road-Metrics Corrector Module
  - alias: corrector
    name: corrector
    version: 1.1.1
    repository: file://./charts/corrector
