---
apiVersion: v1
kind: Service
metadata:
  name: artemis
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
      protocol: TCP
    {{- end }}
  selector:
    app: artemis
