version: 2.1

parameters:
  namespace:
    type: string
    default: sandbox-im
  deploy:
    type: boolean
    default: false

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.1.2
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-docker-images:
    docker:
      - image: cimg/aws:2023.06                
    steps:
      - checkout       
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}'
          aws-region: AWS_DEFAULT_REGION
          profile-name: ${AWS_ROLE}
          role-session-name: CircleSession
          session-duration: '1800' 
      - run:
          name: Create X-Road container images
          command: |
            aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            ./x-road/images/docker-build.sh -p -t latest -r "${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          
  deploy-information-mediator:
    docker:
      - image: cimg/aws:2023.06                
    steps:
      - checkout       
      - aws-cli/setup:
          role-arn: 'arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}'
          aws-region: AWS_DEFAULT_REGION
          profile-name: ${AWS_ROLE}
          role-session-name: CircleSession
          session-duration: '1800' 
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: "${AWS_CLUSTER_NAME}"
          cluster-authentication-role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}        
      - run:
          name: Deploy Information Mediator
          command: |
            helm upgrade --install --atomic \
                --wait --timeout 15m \
                --create-namespace \
                --namespace "<< pipeline.parameters.namespace >>" \
                --set-string xroad-ss.tokenPin="$IM_XROAD_TOKEN_PIN" \
                --set-string xroad-cs.tokenPin="$IM_XROAD_TOKEN_PIN" \
                --set-string global.registry="${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com" \
                sandbox-im-xroad ./x-road/sandbox-im-x-road
      - run:
          name: Verify that X-Road is ready
          command: |
            kubectl -n "<< pipeline.parameters.namespace>>" wait pod --for=condition=Ready --all --timeout 15m
  
workflows:  
  "Deploy IM to EKS cluster":
    jobs:
      - build-docker-images:
          context: aws
      - approve-deploy:
          type: approval
          requires:
            - build-docker-images             
      - deploy-information-mediator:                
          context: aws
          requires:
            - approve-deploy
         
