{{- if .Values.serviceExt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: management-api-ext
  annotations:
    external-dns.alpha.kubernetes.io/evaluateTargetHealth: 'true'
    external-dns.alpha.kubernetes.io/hostname: "management-api.{{ .Values.serviceExt.topLevelDomainName }}"
    service.beta.kubernetes.io/load-balancer-source-ranges: "{{ .Values.serviceExt.subnetAllowList }}"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  selector:
    app: management-api
  ports:
    - protocol: TCP
      port: {{ .Values.managementApi.port }}
  type: LoadBalancer
{{- end }}
