apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corrector.fullname" . }}
  labels:
    {{- include "corrector.labels" . | nindent 4 }}
data:
  settings.yaml: |
    corrector:
      thread-count: {{ .Values.corrector.threadCount }}
      documents-max: {{ .Values.corrector.documentsMax }}
      documents-min: {{ .Values.corrector.documentsMin }}
      timeout-days: {{ .Values.corrector.timeoutDays }}
      wait-on-done: {{ .Values.corrector.waitOnDone }}
      wait-on-error: {{ .Values.corrector.waitOnError }}
      time-window: {{ .Values.corrector.timeWindow }}
      calc:
        total-duration: {{ .Values.corrector.calc.totalDuration }}
        client-request-duration: {{ .Values.corrector.calc.clientRequestDuration }}
        client-response-duration: {{ .Values.corrector.calc.clientResponseDuration }}
        producer-request-duration: {{ .Values.corrector.calc.producerRequestDuration }}
        producer-response-duration: {{ .Values.corrector.calc.producerResponseDuration }}
        producer-duration-client-view: {{ .Values.corrector.calc.producerDurationClientView }}
        producer-duration-producer-view: {{ .Values.corrector.calc.producerDurationProducerView }}
        producer-is-duration: {{ .Values.corrector.calc.producerIsDuration }}
        request-nw-duration: {{ .Values.corrector.calc.requestNwDuration }}
        response-nw-duration: {{ .Values.corrector.calc.responseNwDuration }}
        request-size: {{ .Values.corrector.calc.requestSize }}
        response-size: {{ .Values.corrector.calc.responseSize }}
      comparison-list: {{ toYaml .Values.corrector.comparisonList | nindent 8 }}
      comparison_list_orphan: {{ toYaml .Values.corrector.comparisonListOrphan | nindent 8 }}
    xroad:
      instance: {{ .Values.xroad.instance }}
    mongodb:
      host: {{ .Values.mongodb.host }}
      user: {{ .Values.mongodb.user }}
      password: "PASSWORD_PLACEHOLDER"
      tls: {{ .Values.mongodb.tls }}
      tls-ca-file: {{ .Values.mongodb.tlsCaFile }}
    logger:
      name: {{ .Values.logger.name }}
      module: {{ .Values.logger.module }}
      level: {{ .Values.logger.level }}
      log-path: {{ .Values.logger.logPath }}
      heartbeat-path: {{ .Values.logger.heartbeatPath }}
