{{- if .Values.serviceExt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: messaging-api-ext
  annotations:
    external-dns.alpha.kubernetes.io/evaluateTargetHealth: 'true'
    external-dns.alpha.kubernetes.io/hostname: "messaging-api.{{ .Values.ingress.topLevelDomainName }}"
    service.beta.kubernetes.io/load-balancer-source-ranges: "{{ .Values.ingress.subnetAllowList }}"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  selector:
    app: messaging-api
  ports:
    {{- range .Values.service.ports }}
    - protocol: TCP
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
    {{- end }}
  type: LoadBalancer
{{- end }}
